#7741 - Log.AddMessage level argument desc.
G1ANT-Robot/G1ANT.Addon.Core pull request #4
Opened 2019-05-07 14:29 UTC by Vegebutcher

level argument description added

2019-05-07 14:54 UTC, DanielWilczek requested changes

2019-05-07 14:54 UTC, DanielWilczek commented on G1ANT.Addon.Core/Commands/LogAddMessageCommand.md
> +|`level`| [text](G1ANT.Language/G1ANT.Language/Structures/TextStructure.md) | yes | info | Message log level: `trace`, `debug`, `info`, `warn`, `error` or `fatal` |
Level is required

2019-05-07 14:56 UTC, Vegebutcher commented on G1ANT.Addon.Core/Commands/LogAddMessageCommand.md
> +|`level`| [text](G1ANT.Language/G1ANT.Language/Structures/TextStructure.md) | yes | info | Message log level: `trace`, `debug`, `info`, `warn`, `error` or `fatal` |
```suggestion
|`level`| [text](G1ANT.Language/G1ANT.Language/Structures/TextStructure.md) | no | info | Message log level: `trace`, `debug`, `info`, `warn`, `error` or `fatal` |
```

2019-05-07 15:05 UTC, DanielWilczek approved these changes

2019-05-14 07:32 UTC, WiktoriaPrusik approved these changes

2019-05-14 08:18 UTC, merged